name: Node.js CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2

      - name: Install deps
        run: npm i fsevents@latest -f --save-optional
        
      - name: copy
        run: curl -O https://github.com/mrdoob/three.js/blob/dev/examples/textures/waternormals.jpg
      - name: copy
        run: mkdir node_modules/three/examples/textures
      - name: copy
        run: cp waternormals.jpg node_modules/three/examples/textures

      - name: Build
        run: npm run build
